# Generated by Django 4.2.1 on 2023-10-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='R21',
            fields=[
                ('rank', models.IntegerField(blank=True, db_column='Rank', null=True)),
                ('roll_number', models.CharField(db_column='Roll_Number', max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='utf8mb3_general_ci', db_column='Name', max_length=39)),
                ('branch', models.CharField(db_collation='utf8mb3_general_ci', db_column='Branch', max_length=7)),
                ('username', models.CharField(blank=True, db_collation='utf8mb3_general_ci', db_column='Username', max_length=16, null=True)),
                ('last_login', models.DateField(blank=True, db_column='LAST_LOGIN', null=True)),
                ('mobile', models.BigIntegerField(db_column='Mobile')),
                ('email', models.CharField(db_collation='utf8mb3_general_ci', db_column='Email', max_length=45)),
                ('hackerrank_username', models.CharField(blank=True, db_column='HackerRank_UserName', max_length=20, null=True)),
                ('algorithms_hackerrank_field', models.CharField(db_column='Algorithms(Hackerrank)', max_length=16)),
                ('codechef_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='CodeChef_UserName', max_length=19)),
                ('cc_problems_solved', models.CharField(db_collation='utf8mb3_general_ci', db_column='CC_Problems_Solved', max_length=31)),
                ('total_ccps_10_field', models.CharField(db_collation='utf8mb3_general_ci', db_column='Total(CCPS*10)', max_length=14)),
                ('codeforces_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Codeforces_UserName', max_length=24)),
                ('cf_problems_solved', models.CharField(db_collation='utf8mb3_general_ci', db_column='CF_Problems_Solved', max_length=31)),
                ('total_cfps_10_field', models.CharField(db_collation='utf8mb3_general_ci', db_column='Total(CFPS*10)', max_length=14)),
                ('spoj_username', models.CharField(db_collation='utf8mb3_general_ci', db_column='Spoj_UserName', max_length=19)),
                ('spoj_problems_solved', models.CharField(db_collation='utf8mb3_general_ci', db_column='Spoj_Problems_Solved', max_length=30)),
                ('total_sps_20_field', models.CharField(db_collation='utf8mb3_general_ci', db_column='Total(SPS*20)', max_length=13)),
                ('overall_score', models.IntegerField(db_column='Overall_Score')),
            ],
            options={
                'db_table': 'r21',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_type', models.CharField(max_length=20)),
            ],
        ),
    ]
